CREATE TABLE IF NOT EXISTS "zone_species" (
	"zoneID" UUID NOT NULL,
	"speciesID" UUID NOT NULL,
	CONSTRAINT "FK__zone" FOREIGN KEY ("zoneID") REFERENCES "zone" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT "FK__species" FOREIGN KEY ("speciesID") REFERENCES "species" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT
);