CREATE TABLE IF NOT EXISTS "user_role" (
	"userID" UUID NULL DEFAULT NULL,
	"roleID" INTEGER NULL DEFAULT NULL,
	CONSTRAINT "user_role_roleID_fkey" FOREIGN KEY ("roleID") REFERENCES "role" ("id") ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT "user_role_userID_fkey" FOREIGN KEY ("userID") REFERENCES "user" ("id") ON UPDATE RESTRICT ON DELETE RESTRICT
);