CREATE TABLE IF NOT EXISTS "animal" (
	"id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"speciesID" UUID NOT NULL,
	"name" VARCHAR NOT NULL DEFAULT '',
	"location" POINT NULL DEFAULT NULL,
	"locationTimestamp" TIMESTAMPTZ NULL DEFAULT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "animal_speciesID_fkey" FOREIGN KEY ("speciesID") REFERENCES "species" ("id") ON UPDATE RESTRICT ON DELETE RESTRICT
);