CREATE TABLE "conveyance" (
    "ID" UUID NOT NULL DEFAULT gen_random_uuid(),
	"timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"userID" UUID NOT NULL,
	"messageID" UUID NOT NULL,
	"animalID" UUID NULL,
	"responseID" UUID NULL,
	"alarmID" UUID NULL,
	PRIMARY KEY ("ID"),
	CONSTRAINT "FK__user" FOREIGN KEY ("userID") REFERENCES "user" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT "FK__message" FOREIGN KEY ("messageID") REFERENCES "message" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT "FK__animal" FOREIGN KEY ("animalID") REFERENCES "animal" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT "FK__response" FOREIGN KEY ("responseID") REFERENCES "response" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT "FK__alarm" FOREIGN KEY ("alarmID") REFERENCES "alarm" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT
);