CREATE TABLE "encounter" (
    "ID" UUID NOT NULL DEFAULT gen_random_uuid(),
	"timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"userID" UUID NOT NULL,
    "userLocation" POINT NOT NULL,
	"animalID" UUID NULL,
    "animalLocation" POINT NOT NULL,
	PRIMARY KEY ("ID"),
	CONSTRAINT "FK__user" FOREIGN KEY ("userID") REFERENCES "user" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT "FK__animal" FOREIGN KEY ("animalID") REFERENCES "animal" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT
);