CREATE TABLE IF NOT EXISTS "user_role" (
	"userID" UUID NOT NULL,
	"roleID" INTEGER NOT NULL,
	CONSTRAINT "user_role_roleID_fkey" FOREIGN KEY ("roleID") REFERENCES "role" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT "user_role_userID_fkey" FOREIGN KEY ("userID") REFERENCES "user" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT
);