ALTER TABLE "damageReport"
	ALTER COLUMN "belongingID" TYPE UUID,
	ALTER COLUMN "belongingID" DROP NOT NULL,
	ALTER COLUMN "belongingID" DROP DEFAULT;
ALTER TABLE "damageReport"
	ADD "belonging" VARCHAR NOT NULL DEFAULT '';